# Generated by Django 4.2.4 on 2023-09-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Date Time"
                    ),
                ),
                (
                    "modified_datetime",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Modified Date Time"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(max_length=30, verbose_name="Created By"),
                ),
                (
                    "modified_by",
                    models.CharField(max_length=30, verbose_name="Modified By"),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Event Name")),
                ("index", models.TextField(verbose_name="Event Index")),
                (
                    "start_datetime",
                    models.DateTimeField(verbose_name="Event Start DateTime"),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(verbose_name="Event End DateTime"),
                ),
            ],
            options={
                "verbose_name": "Event",
                "verbose_name_plural": "Events",
                "db_table": "event",
            },
        ),
    ]
