# Generated by Django 4.2.4 on 2023-09-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0003_alter_event_created_by_alter_event_modified_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="created_by",
            field=models.CharField(
                default="system", max_length=30, verbose_name="Created By"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="modified_by",
            field=models.CharField(
                default="system", max_length=30, verbose_name="Modified By"
            ),
        ),
    ]
