# Generated by Django 4.2.4 on 2023-11-19 15:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0004_alter_event_created_by_alter_event_modified_by"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="event",
            table="EVENT",
        ),
    ]
