# Generated by Django 4.2.4 on 2023-11-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0005_alter_event_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="created_by",
            field=models.CharField(
                db_column="EVENT_CREATED_BY",
                default="system",
                max_length=30,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="created_datetime",
            field=models.DateTimeField(
                auto_now_add=True,
                db_column="EVENT_CREATED_DTTM",
                verbose_name="Created Date Time",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="end_date_time",
            field=models.DateTimeField(
                db_column="EVENT_END_DTTM", verbose_name="Event End DateTime"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="id",
            field=models.AutoField(
                db_column="EVENT_PK", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="index",
            field=models.TextField(
                blank=True,
                db_column="EVENT_INDEX",
                null=True,
                verbose_name="Event Index",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="modified_by",
            field=models.CharField(
                db_column="EVENT_MODIFIED_BY",
                default="system",
                max_length=30,
                verbose_name="Modified By",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="modified_datetime",
            field=models.DateTimeField(
                auto_now=True,
                db_column="EVENT_MODIFIED_DTTM",
                verbose_name="Modified Date Time",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="name",
            field=models.CharField(
                db_column="EVENT_NM", max_length=50, verbose_name="Event Name"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_date_time",
            field=models.DateTimeField(
                db_column="EVENT_START_DTTM", verbose_name="Event Start DateTime"
            ),
        ),
    ]
