# Generated by Django 4.2.4 on 2023-11-19 15:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0004_alter_timetable_created_by_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="timetable",
            table="TIMETABLE",
        ),
    ]
