# Generated by Django 4.2.4 on 2023-11-21 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("event", "0006_alter_event_created_by_alter_event_created_datetime_and_more"),
        ("timetable", "0005_alter_timetable_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timetable",
            name="created_by",
            field=models.CharField(
                db_column="TIMETABLE_CREATED_BY",
                default="system",
                max_length=30,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="created_datetime",
            field=models.DateTimeField(
                auto_now_add=True,
                db_column="TIMETABLE_CREATED_DTTM",
                verbose_name="Created Date Time",
            ),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="end_date_time",
            field=models.DateTimeField(
                db_column="TIMETABLE_END_DTTM", verbose_name="Time Table End DateTime"
            ),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="event",
            field=models.ForeignKey(
                db_column="EVENT_EVENT_PK",
                on_delete=django.db.models.deletion.CASCADE,
                to="event.event",
                verbose_name="Related Event",
            ),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="id",
            field=models.AutoField(
                db_column="TIMETABLE_PK", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="index",
            field=models.CharField(
                blank=True,
                db_column="TIMETABLE_INDEX",
                max_length=200,
                null=True,
                verbose_name="Time Table Index",
            ),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="modified_by",
            field=models.CharField(
                db_column="TIMETABLE_MODIFIED_BY",
                default="system",
                max_length=30,
                verbose_name="Modified By",
            ),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="modified_datetime",
            field=models.DateTimeField(
                auto_now=True,
                db_column="TIMETABLE_MODIFIED_DTTM",
                verbose_name="Modified Date Time",
            ),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="name",
            field=models.CharField(
                db_column="TIMETABLE_NM", max_length=50, verbose_name="Time Table Name"
            ),
        ),
        migrations.AlterField(
            model_name="timetable",
            name="start_date_time",
            field=models.DateTimeField(
                db_column="TIMETABLE_START_DTTM",
                verbose_name="Time Table Start DateTime",
            ),
        ),
    ]
