# Generated by Django 4.2.4 on 2023-09-03 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("common", "__first__"),
        ("timetable", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Date Time"
                    ),
                ),
                (
                    "modified_datetime",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Modified Date Time"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(max_length=30, verbose_name="Created By"),
                ),
                (
                    "modified_by",
                    models.CharField(max_length=30, verbose_name="Modified By"),
                ),
                ("name", models.CharField(max_length=45, unique=True)),
            ],
            options={
                "verbose_name": "Attendance Type",
                "verbose_name_plural": "Attendance Types",
                "db_table": "attendance_type",
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_datetime",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created Date Time"
                    ),
                ),
                (
                    "modified_datetime",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Modified Date Time"
                    ),
                ),
                (
                    "created_by",
                    models.CharField(max_length=30, verbose_name="Created By"),
                ),
                (
                    "modified_by",
                    models.CharField(max_length=30, verbose_name="Modified By"),
                ),
                ("index", models.TextField()),
                (
                    "attendance_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="attendance.attendancetype",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="common.member",
                    ),
                ),
                (
                    "time_table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="timetable.timetable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance",
                "verbose_name_plural": "Attendances",
                "db_table": "attendance",
            },
        ),
    ]
