# Generated by Django 4.2.4 on 2023-09-04 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0002_rename_end_datetime_timetable_end_date_time_and_more"),
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=255)),
                ("expire_at", models.DateTimeField(blank=True, null=True)),
                (
                    "time_table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_codes",
                        to="timetable.timetable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attendance Code",
                "verbose_name_plural": "Attendance Codes",
                "unique_together": {("code", "time_table")},
            },
        ),
    ]
