# Generated by Django 4.2.4 on 2023-09-28 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
        ("attendance", "0002_attendancecode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_%(class)s_entities",
                to="common.member",
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="modified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_%(class)s_entities",
                to="common.member",
                verbose_name="Modified By",
            ),
        ),
        migrations.AlterField(
            model_name="attendancetype",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_%(class)s_entities",
                to="common.member",
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="attendancetype",
            name="modified_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_%(class)s_entities",
                to="common.member",
                verbose_name="Modified By",
            ),
        ),
    ]
