# Generated by Django 4.2.4 on 2023-11-19 15:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0004_alter_attendance_created_by_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="attendance",
            table="ATTENDANCE",
        ),
        migrations.AlterModelTable(
            name="attendancetype",
            table="ATTENDANCE_TYPE",
        ),
    ]
