# Generated by Django 4.2.4 on 2023-11-21 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
        ("timetable", "0006_alter_timetable_created_by_and_more"),
        ("attendance", "0005_alter_attendance_table_alter_attendancetype_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attendancetype",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="attendancetype",
            name="created_datetime",
        ),
        migrations.RemoveField(
            model_name="attendancetype",
            name="modified_by",
        ),
        migrations.RemoveField(
            model_name="attendancetype",
            name="modified_datetime",
        ),
        migrations.AlterField(
            model_name="attendance",
            name="attendance_type",
            field=models.ForeignKey(
                db_column="ATTENDANCE_TYPE_ATTENDANCE_TYPE_PK",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="attendance.attendancetype",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="created_by",
            field=models.CharField(
                db_column="ATTENDANCE_CREATED_BY",
                default="system",
                max_length=30,
                verbose_name="Created By",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="created_datetime",
            field=models.DateTimeField(
                auto_now_add=True,
                db_column="ATTENDANCE_CREATED_DTTM",
                verbose_name="Created Date Time",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="id",
            field=models.AutoField(
                db_column="ATTENDANCE_PK", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="index",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="member",
            field=models.ForeignKey(
                db_column="MEMBER_MEMBER_PK",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="common.member",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="modified_by",
            field=models.CharField(
                db_column="ATTENDANCE_MODIFIED_BY",
                default="system",
                max_length=30,
                verbose_name="Modified By",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="modified_datetime",
            field=models.DateTimeField(
                auto_now=True,
                db_column="ATTENDANCE_MODIFIED_DTTM",
                verbose_name="Modified Date Time",
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="time_table",
            field=models.ForeignKey(
                db_column="TIMETABLE_TIMETABLE_PK",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="timetable.timetable",
            ),
        ),
        migrations.AlterField(
            model_name="attendancecode",
            name="code",
            field=models.CharField(db_column="CODE", max_length=255),
        ),
        migrations.AlterField(
            model_name="attendancecode",
            name="expire_at",
            field=models.DateTimeField(blank=True, db_column="EXPIRE_AT", null=True),
        ),
        migrations.AlterField(
            model_name="attendancecode",
            name="time_table",
            field=models.ForeignKey(
                db_column="TIMETABLE_TIMETABLE_PK",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_codes",
                to="timetable.timetable",
            ),
        ),
        migrations.AlterField(
            model_name="attendancetype",
            name="id",
            field=models.AutoField(
                db_column="ATTENDANCE_TYPE_PK", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="attendancetype",
            name="name",
            field=models.CharField(
                db_column="ATTENDANCE_TYPE_NAME", max_length=45, unique=True
            ),
        ),
        migrations.AlterModelTable(
            name="attendancecode",
            table="ATTENDANCE_CODE",
        ),
    ]
