# Generated by Django 4.2.4 on 2023-11-21 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0006_remove_attendancetype_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="index",
            field=models.TextField(blank=True, db_column="ATTENDANCE_INDEX", null=True),
        ),
    ]
